// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenVietTuanAnh0204068De1.DbContexts;

#nullable disable

namespace NguyenVietTuanAnh0204068De1.Migrations
{
    [DbContext(typeof(AppDbContext0204068De1))]
    partial class AppDbContext0204068De1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguyenVietTuanAnh0204068De1.Entities.DoanhNghiep0204068De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDoanhNghiep")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MaSoThue")
                        .IsUnique()
                        .HasDatabaseName("UQ_DoanhNghieps_MaSoThue");

                    b.HasIndex("TenDoanhNghiep")
                        .IsUnique()
                        .HasDatabaseName("UQ_DoanhNghieps_TenDoanhNghiep");

                    b.ToTable("DoanhNghieps", (string)null);
                });

            modelBuilder.Entity("NguyenVietTuanAnh0204068De1.Entities.DoanhNghiepSanPham0204068De1", b =>
                {
                    b.Property<int>("DoanhNghiepId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DoanhNghiepId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("DoanhNghiepSanPhams", (string)null);
                });

            modelBuilder.Entity("NguyenVietTuanAnh0204068De1.Entities.SanPham0204068De1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MaSanPham")
                        .IsUnique()
                        .HasDatabaseName("UQ_SanPhams_MaSanPham");

                    b.HasIndex("TenSanPham")
                        .IsUnique()
                        .HasDatabaseName("UQ_SanPhams_TenSanPham");

                    b.ToTable("SanPhams", (string)null);
                });

            modelBuilder.Entity("NguyenVietTuanAnh0204068De1.Entities.DoanhNghiepSanPham0204068De1", b =>
                {
                    b.HasOne("NguyenVietTuanAnh0204068De1.Entities.DoanhNghiep0204068De1", "DoanhNghiep")
                        .WithMany("DoanhNghiepSanPhams")
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NguyenVietTuanAnh0204068De1.Entities.SanPham0204068De1", "SanPham")
                        .WithMany("DoanhNghiepSanPhams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("NguyenVietTuanAnh0204068De1.Entities.DoanhNghiep0204068De1", b =>
                {
                    b.Navigation("DoanhNghiepSanPhams");
                });

            modelBuilder.Entity("NguyenVietTuanAnh0204068De1.Entities.SanPham0204068De1", b =>
                {
                    b.Navigation("DoanhNghiepSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
